language: node_js
node_js: lts/*
sudo: false

install:
  - yarn

jobs:
  include:
    - stage: Build the Terminal.ink Open Source Bot List project
      script: yarn bundle
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: ./dist
        target_branch: dist
        on:
          branch: ls14
    - script: yarn bundle:gh
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: ./dist
        on:
          branch: ls14
